### ISSUE TITLE
Fails

### ISSUE THREAD

**Issue by samcov** [xcapt/express-filemanager#2]
module.js:338
    throw err;
          ^
Error: Cannot find module 'async'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\Samuel\Desktop\Testbed\express-filemanager-master\filemanager.js:5:13)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by xcapt** [comment]
did you do npm install in the root folder?

**Comment by samcov** [comment]
Ok, that worked! I've never worked with a structure that required installation in two directories under the same root.

I'm sure you have a reason, but I'm happy to see the results, and thanks for responding.

I like what you're doing, but have you given any thought to completely separating the UI from serving up the files?

I need to study your design, but that would give ultimate flexibility, IMO.

**Comment by xcapt** [comment]
Happy to see that it worked for you.

Actually, the project is only the backend adapter for the separate front end project simogeo filemanager thus it cannot be more separated :)

The demo included is just so that users can test and understand how to bind the backend in their own nodejs code.

**Comment by samcov** [comment]
Good to know, and it explains why this version has less capabilities than the Rich version(i.e., unable to drag & drop files).

Good job!

**Comment by xcapt** [comment]
Thanks.
Actually Simogeo filemanager already supported drag and drop, only the upload file window must be brought up first.
